### ISSUE TITLE
No way to turn on SC3-Plugins within the Atom Editor?

### ISSUE THREAD

**Issue by blacknumbers** [KoltesDigital/atom-foxdot#2]

**Comment by KoltesDigital** [comment]
Sorry for the delay, I thought I already replied.

FoxDot manages configuration in a rather static way. This feature would require a change in FoxDot first. I don't have time to do it now, PR welcome.

**Comment by KoltesDigital** [comment]
I made the patch for FoxDot, and the setting is now available from this package (v1.3.0).
