### ISSUE TITLE
How to display FoxDot console in Atom editor?

### ISSUE THREAD

**Issue by funcrab** [KoltesDigital/atom-foxdot#5]
or is it not?

**Comment by KoltesDigital** [comment]
Hm, right now it's not possible, but it makes sense to add this feature. PR welcome!

**Comment by 1a-code** [comment]
thanks!

2019年10月8日(火) 5:23 Jonathan Giroux (Koltes) <notifications@github.com>:

**Comment by sandcobainer** [comment]
Any updates on this? I was planning to do something similar.

**Comment by KoltesDigital** [comment]
I watched a Equinox stream last weekend and I admit it's cumbersome. I'm integrating a separate panel to display console right now.

**Comment by KoltesDigital** [comment]
Published, can you please give it a try?

**Comment by sandcobainer** [comment]
Just tried the console. it works, thank you.

**Comment by 1a-code** [comment]
Thank you @KoltesDigital @sandcobainer .
However, the keybindings don't work on mac.
I'm sorry if it's a problem with my environment.

**Comment by KoltesDigital** [comment]
@1a-code Can you be more specific please? For instance, are you trying to make a key combination, and what is the actual effect?

**Comment by sandcobainer** [comment]
@1a-code They work ok for me. Also, I edited foxdot.json to change keybindings from `ctrl` to `cmd` on my Mac, just a personal preference.

**Comment by 1a-code** [comment]
@sandcobainer Thank you. So it seems to be a problem with my environment, I think it has to do with python and Quarks foxdot updates and basic setups like python2 or 3 and environment variables

@KoltesDigital All my foxdot keybindings didn't work on ATOM, but I think it's fine if I have the right setup.

Building an environment is hard work🤧

**Comment by KoltesDigital** [comment]
@sandcobainer oh right, I never think of Mac. In the native FoxDot, do the keybindings use ctrl or cmd?

**Comment by sandcobainer** [comment]
The native foxdot uses Ctrl on Windows and Cmd on Mac accordingly. Cmd + alphabet might clash with the native Atom keybindings if you're an advanced user. But it's been fine for me.

**Comment by sandcobainer** [comment]
Displaying print statements isn't supported by the Logger service. This might be easy to develop looking at your npm repository. What do you think?

`print(SynthDefs)` or `print(P[0, 1, 2, (3, 4, 5)])` could be useful before executing.

**Comment by KoltesDigital** [comment]
Sorry for the delay! If you find that useful then let's add it... which I did month ago 😄
